### ISSUE TITLE
App.Js Error

### ISSUE THREAD

**Issue by utkarsh-dixit-git** [surya123-ctrl/Bunk4Study-Extension#4]
There is an error in App.js where it shows **./Mycomponents/..../....CDLU-cse/CDLU-CSE not found**
but in app.js code is written **./Mycomponents/.../.../CDLU-CSE That's it.**
So I don't know what's causing this error 
_Any help will be appreciated!_
![e3547224-1da8-468a-bf83-d4fb3fb41485](https://user-images.githubusercontent.com/88888678/179402477-0099b636-cd65-432a-8c16-ecc944b02270.jpg)

@surya123-ctrl @asmitaporwal @PritomDutta89

**Comment by PritomDutta89** [comment]
ok let me check

**Comment by PritomDutta89** [comment]
You made a mistake in the component create. Create the components with the correct name and call it
